INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (1, 'John', 'Doe', 1234567890, 9876543210, '123 Main St', 'john.doe@example.com', 1234567890,'ADMIN','1,2');
INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (2, 'Jane', 'Smith', 2345678901, 8765432109, '456 Elm St', 'jane.smith@example.com', 2345678901,'STAFF','2,4');
INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (3, 'Alice', 'Johnson', 1234567890, 9876543210, '123 Main St', 'john.doe@example.com', 1234567890,'STAFF','5');
INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (4, 'David', 'Williams', 1234567890, 9876543210, '123 Main St', 'john.doe@example.com', 1234567890,'STAFF','8');
INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (5, 'Emily', 'Brown', 1234567890, 9876543210, '123 Main St', 'john.doe@example.com', 1234567890,'STAFF','5');
INSERT INTO STAFF_DETAILS (STAFF_IDENTIFIER, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_NUMBER, SECONDARY_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, WHATSAPP_NUMBER,ROLE,CLASS_OWNED)
VALUES (6, 'Michael', 'Wilson', 5678901234, 5432109876, '789 Pine St', 'michael.wilson@example.com', 5678901234,'STAFF','2,3');





INSERT INTO T_USER (USERNAME, PASSWORD, ACTIVE, ROLES) VALUES ('1234', 'pass','true','ROLE_USER');
INSERT INTO T_USER (USERNAME, PASSWORD, ACTIVE, ROLES) VALUES ('1', 'pass','true','ROLE_USER');
INSERT INTO T_USER (USERNAME, PASSWORD, ACTIVE, ROLES) VALUES ('2', 'pass','true','ROLE_USER');




INSERT INTO STUDENT_DETAILS (STUDENT_IDENTIFIER, FIRST_NAME, LAST_NAME, PARENT_CONTACT_NUMBER, GUARD_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, FATHER_NAME, MOTHER_NAME, GRADE)
VALUES (1234, 'John', 'Doe', 1234567890, 9876543210, '123 Main St', 'john.doe@example.com', 'Michael', 'Sarah', '5');
INSERT INTO STUDENT_DETAILS (STUDENT_IDENTIFIER, FIRST_NAME, LAST_NAME, PARENT_CONTACT_NUMBER, GUARD_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, FATHER_NAME, MOTHER_NAME, GRADE)
VALUES (2123, 'Alice', 'Smith', 2345678901, 8765432109, '456 Elm St', 'alice.smith@example.com', 'David', 'Emily', '3');
INSERT INTO STUDENT_DETAILS (STUDENT_IDENTIFIER, FIRST_NAME, LAST_NAME, PARENT_CONTACT_NUMBER, GUARD_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, FATHER_NAME, MOTHER_NAME, GRADE)
VALUES (3333, 'Emily', 'Johnson', 3456789012, 7654321098, '789 Oak St', 'emily.johnson@example.com', 'Robert', 'Sophia', '8');
INSERT INTO STUDENT_DETAILS (STUDENT_IDENTIFIER, FIRST_NAME, LAST_NAME, PARENT_CONTACT_NUMBER, GUARD_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, FATHER_NAME, MOTHER_NAME, GRADE)
VALUES (4321, 'James', 'Williams', 4567890123, 6543210987, '567 Pine St', 'james.williams@example.com', 'Daniel', 'Olivia', '2');
INSERT INTO STUDENT_DETAILS (STUDENT_IDENTIFIER, FIRST_NAME, LAST_NAME, PARENT_CONTACT_NUMBER, GUARD_CONTACT_NUMBER, ADDRESS_TEXT, EMAIL_IDENTIFIER, FATHER_NAME, MOTHER_NAME, GRADE)
VALUES (5223, 'Sophia', 'Brown', 5678901234, 5432109876, '890 Cedar St', 'sophia.brown@example.com', 'Christopher', 'Ava', '6');
	

